name 'devops_script'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures devops_script'
long_description 'Installs/Configures devops_script'
version '0.1.0'
